// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnwN0BZ3M_VfHoUyN8rajIYz1MeF0Gws',
    appId: '1:81226293678:web:13b6536749b51463eda83f',
    messagingSenderId: '81226293678',
    projectId: 'flutterfirebaseeducated-b33cc',
    authDomain: 'flutterfirebaseeducated-b33cc.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-b33cc.firebasestorage.app',
    measurementId: 'G-26JELSXKG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBidWADeA3P9FzW5aDHgaa0W3fd4VdASY',
    appId: '1:81226293678:android:623dc70179dc4f1eeda83f',
    messagingSenderId: '81226293678',
    projectId: 'flutterfirebaseeducated-b33cc',
    storageBucket: 'flutterfirebaseeducated-b33cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8ZDWgg2qu7ofoKBxAJvk3yZ-7XhBU8w',
    appId: '1:81226293678:ios:96e6058a852d9dc6eda83f',
    messagingSenderId: '81226293678',
    projectId: 'flutterfirebaseeducated-b33cc',
    storageBucket: 'flutterfirebaseeducated-b33cc.firebasestorage.app',
    iosBundleId: 'com.example.electricityPayment',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ8ZDWgg2qu7ofoKBxAJvk3yZ-7XhBU8w',
    appId: '1:81226293678:ios:96e6058a852d9dc6eda83f',
    messagingSenderId: '81226293678',
    projectId: 'flutterfirebaseeducated-b33cc',
    storageBucket: 'flutterfirebaseeducated-b33cc.firebasestorage.app',
    iosBundleId: 'com.example.electricityPayment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgnwN0BZ3M_VfHoUyN8rajIYz1MeF0Gws',
    appId: '1:81226293678:web:8cf69b5a2b43fb49eda83f',
    messagingSenderId: '81226293678',
    projectId: 'flutterfirebaseeducated-b33cc',
    authDomain: 'flutterfirebaseeducated-b33cc.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-b33cc.firebasestorage.app',
    measurementId: 'G-WKY17TX0QY',
  );
}
