// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_y8NsjgTSArNSML6aOp4DMdcYrVCNZW8',
    appId: '1:48437781644:web:6757a0b9c717746f31c7a9',
    messagingSenderId: '48437781644',
    projectId: 'flutterfirebaseeducated-1d35d',
    authDomain: 'flutterfirebaseeducated-1d35d.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-1d35d.firebasestorage.app',
    measurementId: 'G-E1CTEG1H65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XhZvB-YdQybKBOdnN0-v7-3UQb8O6YI',
    appId: '1:48437781644:android:a6d2d70614f70ff431c7a9',
    messagingSenderId: '48437781644',
    projectId: 'flutterfirebaseeducated-1d35d',
    storageBucket: 'flutterfirebaseeducated-1d35d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO7F-LDE7Wafuh-s699-makkT9eBDjcgY',
    appId: '1:48437781644:ios:f139f80a67fd26c531c7a9',
    messagingSenderId: '48437781644',
    projectId: 'flutterfirebaseeducated-1d35d',
    storageBucket: 'flutterfirebaseeducated-1d35d.firebasestorage.app',
    iosBundleId: 'com.example.electricityPayment',
  );
}
